In [27]:
import pandas as pd
from datetime import datetime

In [28]:
input_path="sample_data/retail_db/order_items/part-00000-order_items.csv"

In [29]:
# Read the input CSV file
df = pd.read_csv(input_path)
df.head(5)

,order_item_id,order_item_order_id,order_item_product_id,order_item_quantity,order_item_subtotal,order_item_product_price
0,1,1,957,1,299.98,299.98
1,2,2,1073,1,199.99,199.99
2,3,2,502,5,250.00,50.00
3,4,2,403,1,129.99,129.99
4,5,4,897,2,49.98,24.99

In [30]:
# 1. Add a discount column (e.g., 10% discount on subtotal for demonstration purposes)
df['discounted_price'] = (df['order_item_subtotal'] * 0.9).round(2)
df.head()

,order_item_id,order_item_order_id,order_item_product_id,order_item_quantity,order_item_subtotal,order_item_product_price,discounted_price
0,1,1,957,1,299.98,299.98,269.98
1,2,2,1073,1,199.99,199.99,179.99
2,3,2,502,5,250.00,50.00,225.00
3,4,2,403,1,129.99,129.99,116.99
4,5,4,897,2,49.98,24.99,44.98

In [31]:
# 2. Add a new column with ingestion timestamp
df['ingestion_timestamp'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
df.head(5)

,order_item_id,order_item_order_id,order_item_product_id,order_item_quantity,order_item_subtotal,order_item_product_price,discounted_price,ingestion_timestamp
0,1,1,957,1,299.98,299.98,269.98,2025-03-17 17:14:39
1,2,2,1073,1,199.99,199.99,179.99,2025-03-17 17:14:39
2,3,2,502,5,250.00,50.00,225.00,2025-03-17 17:14:39
3,4,2,403,1,129.99,129.99,116.99,2025-03-17 17:14:39
4,5,4,897,2,49.98,24.99,44.98,2025-03-17 17:14:39

In [ ]:
# Remove the column 'order_item_product_price'
df = df.drop(columns=['order_item_product_price'])

In [32]:
# Write the transformed DataFrame to the output path
# Save the data in a single CSV file, ensuring overwrite mode
output_path ="sample_data/retail_db/order_items/op.csv"
df.to_csv(output_path, index=False)